### ISSUE TITLE
缺少了一些类

### ISSUE THREAD

**Issue by xuqijia** [ysh-1998/CoWPiRec#1]
您好，CoWPiRecDataset、CustomizedFullSortEvalDataLoader、CustomizedFullSortEvalDataLoader未找到，请问可以重新传一下吗
另外，预训练的模型貌似无法下载了

**Comment by ysh-1998** [comment]
感谢您的关注，抱歉回复迟了。

**Comment by ysh-1998** [comment]
感谢您的关注，抱歉回复迟了。
问题1是由于我们在迭代代码时忘记了删除弃用module的import语句，您可以简单的删除这两个模型的import即可，我们也已经在代码中修复了这个问题
关于问题2，我们在最新的README中增加一个google driver [link](https://drive.google.com/drive/folders/1VzGNSaEFp8T3ongi5mIHAeCf1gDQxhSS?usp=sharing)用于下载预训练模型
